version: '3'
services:
  etcd: 
    image: quay.io/coreos/etcd
    container_name: etcd${ID}

    command:
      etcd
      -name ${ETCD_NAME}
      -initial-advertise-peer-urls http://${LOCAL_IP}:${PORT_1}
      -listen-peer-urls http://0.0.0.0:${PORT_1}
      -listen-client-urls http://0.0.0.0:${PORT_0}
      -advertise-client-urls http://${LOCAL_IP}:${PORT_0}
      -initial-cluster-token ${ETCD_INITIAL_CLUSTER_TOKEN}
      -initial-cluster ${ETCD_INITIAL_CLUSTER}
      -initial-cluster-state ${ETCD_INITIAL_CLUSTER_STATE}
      -data-dir /etc/data

    ports:
      - ${PORT_0}:${PORT_0}
      - ${PORT_1}:${PORT_1}

    volumes:
      - ${LOCAL_DATA_DIR}:/etc/data

    restart: always
